# Generated by Django 4.2.5 on 2023-09-16 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('grade', models.DecimalField(choices=[(0.0, '0점'), (0.5, '0.5점'), (1.0, '1점'), (1.5, '1.5점'), (2.0, '2점'), (2.5, '2.5점'), (3.0, '3점'), (3.5, '3.5점'), (4.0, '4점'), (4.5, '4.5점'), (5.0, '5점')], decimal_places=1, max_digits=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
