# Generated by Django 4.2.5 on 2023-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(choices=[(0.0, '0점'), (0.5, '0.5점'), (1.0, '1점'), (1.5, '1.5점'), (2.0, '2점'), (2.5, '2.5점'), (3.0, '3점'), (3.5, '3.5점'), (4.0, '4점'), (4.5, '4.5점'), (5.0, '5점')]),
        ),
    ]
